/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mio.GUI.form;

import com.mio.BLL.TeacherBLL;
import com.mio.BLL.UserBLL;
import com.mio.DTO.Department;
import com.mio.DTO.Teacher;
import com.mio.DTO.User;
import com.mio.GUI.dialog.UserInforDialog;
import com.mio.GUI.main.Main;
import java.util.List;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Mio
 */
public class AdminFormTeacher extends javax.swing.JPanel {

    List<Teacher> list;
    Department dep;
    AdminFormDepartment parent;
    
    public AdminFormTeacher(Department dep, AdminFormDepartment parent) {
        initComponents();
        
        this.dep = dep;
        this.parent = parent;
        
        menuSplit1.setText("Khoa " + dep.getName());
        
        table.fixTable(scrollPane);
        table.setModel(new MyModel(list = TeacherBLL.getInstance().getTeacherList(dep.getId())));
    }
    private class MyModel extends AbstractTableModel {
        List<Teacher> list;
        MyModel(List<Teacher> list) {
            this.list = list;
        }

        @Override
        public String getColumnName(int column) {
            switch (column) {
                case 0 -> {
                    return "Mã số";
                }
                case 1 -> {
                    return "Họ và tên";
                }
                case 2 -> {
                    return "Số điện thoại";
                }
                case 3 -> {
                    return "Giới tính";
                }
                default -> {
                    return "Ngày sinh";
                }
            }
        }
        
        
        @Override
        public int getColumnCount() {
            return 5;
        }

        @Override
        public int getRowCount() {
            return list.size();
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Teacher teacher = list.get(rowIndex);
            switch(columnIndex) {
                case 0 -> {
                    return teacher.getId();
                }
                case 1 -> {
                    return teacher.getName();
                }
                case 2 -> {
                    return teacher.getPhoneNumber();
                }
                case 3 -> {
                    return teacher.isMale() ? "Nam" : "Nữ";
                }
                default -> {
                    return teacher.getBirthday();
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuSplit1 = new com.mio.GUI.swing.MenuSplit();
        btnTeacherAdd = new com.mio.GUI.swing.Button();
        btnTeacherEdit = new com.mio.GUI.swing.Button();
        btnTeacherDel = new com.mio.GUI.swing.Button();
        scrollPane = new javax.swing.JScrollPane();
        table = new com.mio.GUI.swing.MyTable();
        btnBack = new com.mio.GUI.swing.ActionButton();

        setOpaque(false);

        btnTeacherAdd.setText("Thêm");
        btnTeacherAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherAddActionPerformed(evt);
            }
        });

        btnTeacherEdit.setText("Sửa");
        btnTeacherEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherEditActionPerformed(evt);
            }
        });

        btnTeacherDel.setText("Xóa");
        btnTeacherDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherDelActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Họ và tên", "SĐT", "Giới tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
        }

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mio/GUI/icon/back_16.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(scrollPane)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnTeacherAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTeacherEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTeacherDel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuSplit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuSplit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTeacherAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeacherEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeacherDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTeacherAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherAddActionPerformed
        Object[] o = new UserInforDialog(Main.getInstance(), null, User.UserRole.TEACHER).showDialog();
        if(o != null) {
            Teacher t = (Teacher)o[0];
            t.setDepartmentId(dep.getId());
            User u = new User(-1, (String)o[1], User.UserRole.TEACHER);
            
            if(TeacherBLL.getInstance().addTeacher(u, t)) {
                list.add(t);
                ((MyModel)table.getModel()).fireTableRowsInserted(list.size() - 1, list.size() - 1);
            } else {
                Main.getInstance().showNotification(Main.NotificationType.ADD_FAILED);
            }
        }

    }//GEN-LAST:event_btnTeacherAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Main.getInstance().showForm(parent);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTeacherEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherEditActionPerformed
        int r = table.getSelectedRow();
        if(r != -1) {
            Teacher t = list.get(r);
            Object[] o = new UserInforDialog(Main.getInstance(), t, User.UserRole.TEACHER).showDialog();
            if(o != null) {
                Teacher edit = (Teacher)o[0];
                edit.setId(t.getId());
                edit.setDepartmentId(t.getDepartmentId());
                if(TeacherBLL.getInstance().updateTeacher(edit)) {
                    list.get(r).copy(edit);
                    ((MyModel)table.getModel()).fireTableRowsUpdated(r, r);
                } else {
                    Main.getInstance().showNotification(Main.NotificationType.UPDATE_FAILED);
                }
            }
        }
    }//GEN-LAST:event_btnTeacherEditActionPerformed

    private void btnTeacherDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherDelActionPerformed
        int r = table.getSelectedRow();
        if(r != -1) {
            if(TeacherBLL.getInstance().delTeacher(list.get(r).getId())) {
                UserBLL.getInstance().deleteUser(list.get(r).getId());
                list.remove(r);
                ((MyModel)table.getModel()).fireTableRowsDeleted(r, r);
            } else {
                Main.getInstance().showNotification(Main.NotificationType.DELETE_FAILED);
            }
        }
    }//GEN-LAST:event_btnTeacherDelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mio.GUI.swing.ActionButton btnBack;
    private com.mio.GUI.swing.Button btnTeacherAdd;
    private com.mio.GUI.swing.Button btnTeacherDel;
    private com.mio.GUI.swing.Button btnTeacherEdit;
    private com.mio.GUI.swing.MenuSplit menuSplit1;
    private javax.swing.JScrollPane scrollPane;
    private com.mio.GUI.swing.MyTable table;
    // End of variables declaration//GEN-END:variables
}
